name: credits
description: Show a simple end credits that includes any type of widgets as you wish.
version: 1.0.1
homepage: https://github.com/sameteyisan/credits.git

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: